Proyecto_2/Clinica/Clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from appbase.views import InicioView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('base/', include('appbase.urls')),
    path('atencion/', include('appconsulta.urls')),
    path('',  auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Proyecto_2/Clinica/appbase/urls.py
from django.urls import path
from .views import(PacienteView, CrearPacienteView, EditarPacienteView, EliminarPacienteView, 
ListadoHorarioView, CrearHorarioView, EditarHorarioView, EliminarHorarioView, ListadoAgendaView,
CrearAgendaView, EditarAgendaView, EliminarAgendaView, DoctorView, CrearDoctoresView, EditarDoctoresView,
EliminarDoctoresView, SignoVitalView, CrearSignoVitalView, EditarSignoVitalView, EliminarSignoVitalView)
app_name = 'base'
urlpatterns = [
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    path('listar_horario/', ListadoHorarioView.as_view(), name='listar_horario'),
    path('crear_horario/', CrearHorarioView.as_view(), name='crear_horario'),
    path('editar_horario/<int:pk>/', EditarHorarioView.as_view(), name='editar_horario'),
    path('eliminar_horario/<int:pk>/', EliminarHorarioView.as_view(), name='eliminar_horario'),
    path('listar_agenda/', ListadoAgendaView.as_view(), name='listar_agenda'),
    path('crear_agenda/', CrearAgendaView.as_view(), name='crear_agenda'),
    path('editar_agenda/<int:pk>/', EditarAgendaView.as_view(), name='editar_agenda'),
    path('eliminar_agenda/<int:pk>/', EliminarAgendaView.as_view(), name='eliminar_agenda'),
    path('listar_doctores/', DoctorView.as_view(), name='listar_doctores'),
    path('crear_doctores/', CrearDoctoresView.as_view(), name='crear_doctores'),
    path('editar_doctores/<int:pk>/',
         EditarDoctoresView.as_view(), name='editar_doctores'),
    path('eliminar_doctores/<int:pk>/',
         EliminarDoctoresView.as_view(), name='eliminar_doctores'),
    path('listar_signovital/', SignoVitalView.as_view(), name='listar_signovital'),
    path('crear_signovital/', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(), name='editar_signovital'),
    path('eliminar_signovital/<int:pk>/', EliminarSignoVitalView.as_view(), name='eliminar_signovital'),
]

Proyecto_2/Clinica/appconsulta/urls.py
from django.urls import path
from .views import HistoriaView2, RecetasPacientes, NuevaRecetaPacientes, DetalleRecetaPacientes, DetalleRecetas, TomaSignosPacientes
app_name = "atencion"
urlpatterns = [
    path('historia/', HistoriaView2.as_view(), name='historia'),
    path('recetas/', RecetasPacientes.as_view(), name='recetas'),
    path('nuevaReceta/', NuevaRecetaPacientes.as_view(), name='nuevaReceta'),
    path('detalleReceta/',DetalleRecetaPacientes.as_view(), name='detalle'),
    path('detalleRecetaP/',DetalleRecetas.as_view(), name='d'),
    path('tomaSigno/',TomaSignosPacientes.as_view(), name='toma')
]

Proyecto_2/Clinica/templates/base/paciente/paciente.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                    <h3 id="titulo" class="font-weight-bold" onclick="convertir()">{{titulo}}</h3>
                </div>
                <div class="col-md-4 ">
                    <a href="{% url 'base:crear_paciente' %}" class="btn btn-primary float-right">Nuevo Registro</a>
                </div>

            </div>
        </div>
        <div class="card-body table-responsive">

            <form class="row">

                <div class="col-md-8">
                    <input class="form-control mr-2 bg-info text-danger font-weight-bold " placeholder="Texto a Buscar"
                        name="nombre" value={{nombre}}>
                </div>
                <div class="col-md-4 ">
                    <button class="btn btn-primary" type="submit">Buscar</button>
                    <a class="btn btn-primary " href="{% url 'atencion:nuevaReceta' %}">Nueva Receta</a>

                </div>
            </form>

            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Foto</th>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Genero</th>
                                <th class="text-center">Correo</th>
                                <th class="text-center">Telefono</th>
                                <th class="text-center">Ciudad</th>
                                <th class="text-center">Direccion</th>
                                <th class="text-center">Acciones</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for paciente in pacientes%}
                            <tr>
                                {% if paciente.foto %}
                                <td class="text-center"><img src="{{paciente.foto.url}}" class="img-thumbnail rounded-circle" width="40px">
                                </td>
                                {% else %}
                                <td class="text-center"><img src="{% static 'imagenes/sinimagen.png' %}"
                                        class="img-thumbnail rounded-circle" width="40px">
                                </td>
                                {% endif %}

                                <td class="text-center"><span>{{paciente.nombre}}</span> </td>
                                {% if paciente.sexo == 'M' %}
                                <td class="text-center"><span
                                        class="badge badge-pill badge-success">{{paciente.sexo}}</span>
                                </td>
                                {% else %}
                                <td class="text-center"><span
                                        class="badge badge-pill badge-danger">{{paciente.sexo}}</span>
                                </td>
                                {% endif %}

                                <td class="text-center">{{paciente.email}}</td>
                                <td class="text-center">{{paciente.telefono}}</td>
                                <td class="text-center">{{paciente.ciudad}}</td>
                                <td class="text-center">{{paciente.direccion}}</td>

                                <td class="text-center">
                                    <a class="btn btn-primary btn-sm"
                                        href="{% url 'base:editar_paciente' paciente.id %}">Editar</a>
                                    <a class="btn btn-primary btn-sm"
                                        href="{% url 'atencion:recetas' %}?id_paciente={{paciente.id}}">Receta</a>
                                    <a class="btn btn-primary btn-sm"
                                        href="{% url 'atencion:historia' %}?id_paciente={{paciente.id}}">Historia</a>
                                    <a rel="action" data-json='{"accion":"elim" ,"id":"{{paciente.id}}"}'
                                        class="btn btn-danger btn-sm" href="#">Eliminar</a>
                                </td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen Pacientes registrados
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- Menú de paginación -->
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item ">
                        <a class="page-link"
                            href="?nombre={{nombre}}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                    </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if i <= page_obj.number|add:2 and i >= page_obj.number|add:-2 %}
                    {% if page_obj.number == i %}
                    <li class="page-item active" style="pointer-events:none">
                        <a href="#" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{ forloop.counter }}{{ url }}" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item ">
                        <a class="page-link" href="?nombre={{nombre}}&page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            <!-- Fin del pagineo -->
        </div>
    </div>



</div>
{% endblock %}

{% block frmodal %}
<!-- inicio formulario Modal para Eliminar -->

<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:eliminar_paciente' 0 %} ">
                {% csrf_token %}
                <div class="modal-header bg-primary text-light">
                    <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" id="id" value="">
                    <input type="hidden" name="action" value="elim">
                    <div class="h3 text-center">
                        <label class="text-primary font-weight-bold">Esta Seguro De Eliminar El Paciente:</label>
                        <span class="text-light font-weight-bold badge badge-danger badge-pill"
                            id="descripcion"></span><br>

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Final Formulario Modal-->
{% endblock %}

{% block jscript %}
<script>
    $(function () {

        $('#tabla').on('click', 'a[rel="action"]', function () {
            let data = $(this).data('json'),
                action = data.accion,
                id = data.id;
            let desc = $(this).parents('tr').children('td').eq(1).html();
            $('#descripcion').html(desc);
            $('#frmEliminar #id').val(id);
            $('#myModal').modal('show');
            return;

        });

    })

    function convertir() {
        let titulo = document.getElementById("titulo").innerText
        document.getElementById("titulo").innerText = titulo.toUpperCase()
        alert(titulo)
    }
</script>
{% endblock %}

Proyecto_2/Clinica/templates/base/paciente/registrar_paciente.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                    <h3 class="font-weight-bold">Mantenimiento de Pacientes</h3>
                </div>
                <div class="col-md-4 ">
                    <a href="{% url 'base:paciente' %}" class="btn btn-primary float-right">Cancelar</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="col-md-12">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- {{ form.as_p }} -->
                    <!-- <div class="form-group row">
                        <label class="col-sm-2 col-form-label"
                            for="id_{{ form.nombre.name }}">{{form.nombre.label}}</label>
                        <div class="col-sm-4>
                            {{form.nombre}} 
                        </div>
                        <label class="col-sm-2 col-form-label"
                            for="id_{{ form.apellido.name }}">{{form.apellido.label}}</label>
                        <div class="col-sm-4>
                            {{form.apellido}} 
                        </div>

                    </div> -->
                    {% if form.errors %}
                    <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                        <strong> {{ form.errors}}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                    {% for campo in form %}
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label" for="id_{{ campo.name }}">{{campo.label}}</label>
                        <div class="col-md-10">
                            {{campo}}
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn btn-success btn-block" type="submit">Registrar</button>

                </form>
            </div>


        </div>
    </div>

</div>
{% endblock %}

{% block jscript %}
<script>
    $(function () {


    })

</script>
{% endblock %}