Proyecto_2/Clinica/Clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from appbase.views import InicioView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('base/', include('appbase.urls')),
    path('atencion/', include('appconsulta.urls')),
    path('',  auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Proyecto_2/Clinica/appbase/urls.py
from django.urls import path
from .views import(PacienteView, CrearPacienteView, EditarPacienteView, EliminarPacienteView, 
ListadoHorarioView, CrearHorarioView, EditarHorarioView, EliminarHorarioView, ListadoAgendaView,
CrearAgendaView, EditarAgendaView, EliminarAgendaView, DoctorView, CrearDoctoresView, EditarDoctoresView,
EliminarDoctoresView, SignoVitalView, CrearSignoVitalView, EditarSignoVitalView, EliminarSignoVitalView)
app_name = 'base'
urlpatterns = [
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    path('listar_horario/', ListadoHorarioView.as_view(), name='listar_horario'),
    path('crear_horario/', CrearHorarioView.as_view(), name='crear_horario'),
    path('editar_horario/<int:pk>/', EditarHorarioView.as_view(), name='editar_horario'),
    path('eliminar_horario/<int:pk>/', EliminarHorarioView.as_view(), name='eliminar_horario'),
    path('listar_agenda/', ListadoAgendaView.as_view(), name='listar_agenda'),
    path('crear_agenda/', CrearAgendaView.as_view(), name='crear_agenda'),
    path('editar_agenda/<int:pk>/', EditarAgendaView.as_view(), name='editar_agenda'),
    path('eliminar_agenda/<int:pk>/', EliminarAgendaView.as_view(), name='eliminar_agenda'),
    path('listar_doctores/', DoctorView.as_view(), name='listar_doctores'),
    path('crear_doctores/', CrearDoctoresView.as_view(), name='crear_doctores'),
    path('editar_doctores/<int:pk>/',
         EditarDoctoresView.as_view(), name='editar_doctores'),
    path('eliminar_doctores/<int:pk>/',
         EliminarDoctoresView.as_view(), name='eliminar_doctores'),
    path('listar_signovital/', SignoVitalView.as_view(), name='listar_signovital'),
    path('crear_signovital/', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(), name='editar_signovital'),
    path('eliminar_signovital/<int:pk>/', EliminarSignoVitalView.as_view(), name='eliminar_signovital'),
]

Proyecto_2/Clinica/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Heartland</title>
    {% load static%}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- datepicker-->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.css">
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">

    {% block headcss %}

    {% endblock %}

</head>

<body>
    <header>
        {% block header %}

        {% endblock %}
    </header>
    <main>
        {% block main %}
        {% endblock %}
    </main>
    <footer>
        {% block footer %}
        {% endblock %}
    </footer>

    {% block frmodal %}

    {% endblock %}



    <!-- En el orden jQuery, Popper.js y Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.js"></script>


    {% block js %}

    {% endblock %}

    {% block jscript %}

    {% endblock %}
</body>

</html>

Proyecto_2/Clinica/templates/header.html
{% load static %}
<nav class="navbar navbar-landing fixed-top navbar-expand-lg  navbar-light  p-0" style="background-color: #6ac1ff;">
    <a class="navbar-brand" href="#">
        <span class="text-light font-weight-bold"><img src="{% static 'imagenes/logo.png' %}"
                width="20px">eartland</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active ">
                <a class="btn btn-primary " data-toggle="tooltip" data-placement="bottom" title=""
                    data-original-title="Menu Principal" href="{% url 'inicio' %}"> Inicio<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class=" btn btn-flat-info btn-small" data-toggle="tooltip" data-placement="top" title=""
                    data-original-title="Administracion de Entidades" href="/admin"><span
                        class="text-white">Administracion</span></a>
            </li>
            <li class="nav-item">
                <a class="btn btn-flat-info btn-small" data-toggle="tooltip" data-placement="bottom" title=""
                    data-original-title="Atencion de Pacientes" href="{% url 'base:paciente' %}"><span
                        class="text-white">
                        Atencion</span></a>
            </li>

            <li class="nav-item">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown ">
                    <button type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="right" title=""
                        data-original-title="Reportes Gerenciales">Agenda</button>
                    <div class="btn-group show" role="group">
                        <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
                        <div class="dropdown-menu " aria-labelledby="btnGroupDrop1"
                            style="position: absolute; transform: translate3d(0px, 34px, 0px); top: 0px; left: 0px; will-change: transform;"
                            x-placement="bottom-start">
                            <a class="dropdown-item" href="{% url 'base:listar_horario' %}">Horarios</a>
                            <a class="dropdown-item" href="{% url 'base:listar_doctores' %}">Doctor</a>
                            <a class="dropdown-item" href="{% url 'base:listar_agenda' %}">Citas</a>
                            <a class="dropdown-item" href="{% url 'base:listar_signovital' %}">Signo Vitales</a>

                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link active" href="#">
                    Usuario: {{ user.username }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'logout' %}">
                    Cerrar Sesión 
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<!-- menu vertical Sidenav -->

Proyecto_2/Clinica/templates/index.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static%}
<div class="container" style="margin-top: 2rem;">

    <div id="carouselExampleCaptions" class="carousel slide" data-ride="c   arousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'imagenes/consultorio1.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'imagenes/consultorio2.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'imagenes/consultorio3.jpg' %}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
{% endblock %}

{% block jscript %}
<script>
    $(function () {
        ('.carousel').carousel()

    })
</script>
{% endblock %}