Proyecto_2/Clinica/Clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from appbase.views import InicioView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('base/', include('appbase.urls')),
    path('atencion/', include('appconsulta.urls')),
    path('',  auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Proyecto_2/Clinica/appbase/urls.py
from django.urls import path
from .views import(PacienteView, CrearPacienteView, EditarPacienteView, EliminarPacienteView, 
ListadoHorarioView, CrearHorarioView, EditarHorarioView, EliminarHorarioView, ListadoAgendaView,
CrearAgendaView, EditarAgendaView, EliminarAgendaView, DoctorView, CrearDoctoresView, EditarDoctoresView,
EliminarDoctoresView, SignoVitalView, CrearSignoVitalView, EditarSignoVitalView, EliminarSignoVitalView)
app_name = 'base'
urlpatterns = [
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    path('listar_horario/', ListadoHorarioView.as_view(), name='listar_horario'),
    path('crear_horario/', CrearHorarioView.as_view(), name='crear_horario'),
    path('editar_horario/<int:pk>/', EditarHorarioView.as_view(), name='editar_horario'),
    path('eliminar_horario/<int:pk>/', EliminarHorarioView.as_view(), name='eliminar_horario'),
    path('listar_agenda/', ListadoAgendaView.as_view(), name='listar_agenda'),
    path('crear_agenda/', CrearAgendaView.as_view(), name='crear_agenda'),
    path('editar_agenda/<int:pk>/', EditarAgendaView.as_view(), name='editar_agenda'),
    path('eliminar_agenda/<int:pk>/', EliminarAgendaView.as_view(), name='eliminar_agenda'),
    path('listar_doctores/', DoctorView.as_view(), name='listar_doctores'),
    path('crear_doctores/', CrearDoctoresView.as_view(), name='crear_doctores'),
    path('editar_doctores/<int:pk>/',
         EditarDoctoresView.as_view(), name='editar_doctores'),
    path('eliminar_doctores/<int:pk>/',
         EliminarDoctoresView.as_view(), name='eliminar_doctores'),
    path('listar_signovital/', SignoVitalView.as_view(), name='listar_signovital'),
    path('crear_signovital/', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(), name='editar_signovital'),
    path('eliminar_signovital/<int:pk>/', EliminarSignoVitalView.as_view(), name='eliminar_signovital'),
]

Proyecto_2/Clinica/appconsulta/urls.py
from django.urls import path
from .views import HistoriaView2, RecetasPacientes, NuevaRecetaPacientes, DetalleRecetaPacientes, DetalleRecetas, TomaSignosPacientes
app_name = "atencion"
urlpatterns = [
    path('historia/', HistoriaView2.as_view(), name='historia'),
    path('recetas/', RecetasPacientes.as_view(), name='recetas'),
    path('nuevaReceta/', NuevaRecetaPacientes.as_view(), name='nuevaReceta'),
    path('detalleReceta/',DetalleRecetaPacientes.as_view(), name='detalle'),
    path('detalleRecetaP/',DetalleRecetas.as_view(), name='d'),
    path('tomaSigno/',TomaSignosPacientes.as_view(), name='toma')
]

Proyecto_2/Clinica/templates/atencion/receta/crear_receta.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-herader rounded-top bg-success shadow p-0">
                    <div class="row">
                        <div class="card-title col-md-8 mt-2">
                            <h2 class="text-light ml-2 font-italic font-weight-bold">
                                Mantenimiento De Recetas 
                            </h2>
                        </div>
                        <div class="col-md-4">
                            <div class="float-right m-3">
                                <a href="{% url 'base:paciente' %}" class="btn btn-primary">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}

                                <button class="btn btn-success btn-block"
                                type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Proyecto_2/Clinica/templates/atencion/receta/detalle.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-herader rounded-top bg-success shadow p-0">
                    <div class="row">
                        <div class="card-title col-md-8 mt-2">
                            <h2 class="text-light ml-2 font-italic font-weight-bold">
                                Mantenimiento De Recetas 
                            </h2>
                        </div>
                        <div class="col-md-4">
                            <div class="float-right m-3">
                                <a href="{% url 'base:paciente' %}" class="btn btn-primary">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}

                                <button class="btn btn-success btn-block"
                                type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Proyecto_2/Clinica/templates/atencion/receta/detalle_de_receta.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                </div>
            </div>
        </div>
        <div class="card-body table-responsive">
            <div class="row">
                <div class="card-title col-md-8 mt-2">
                    <h2 class="text-dark ml-2 font-italic">
                        Consulta de Recetas del paciente. 
                    </h2>
                </div>
            </div>
            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Receta</th>
                                <th class="text-center">Medicamento</th>
                                <th class="text-center">Cantidad</th>
                                <th class="text-center">Dosis</th>
                                <th class="text-center">Frecuencias</th>
                                <th class="text-center">Duracion</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for rec in recetasD%}
                            <tr>
                                <td class="text-center">{{ rec.receta }}</td>
                                <td class="text-center">{{ rec.medicamento.descripcion }}</td>
                                <td class="text-center">{{ rec.cantidad }}</td>
                                <td class="text-center">{{ rec.dosis.descripcion }}</td>
                                <td class="text-center">{{ rec.frecuencia.descripcion }}</td>
                                <td class="text-center">{{ rec.duracion.descripcion }}</td>
                            </tr>
                            <div class="float-right m-3">
                                <a class="btn btn-primary btn-sm"
                                href="{% url 'atencion:recetas' %}?id_paciente={{rec.receta.paciente.id}}">Cancelar</a>
        
                            </div>
                            {% empty %}
                            <div class="row">
                                <div class="col-md-8">
                                </div>
                                <div class="col-md-4 ">
                                    <div class="float-right m-1">
                                        <a class="btn btn-primary btn-sm"
                                        href="{% url 'base:paciente' %}">Cancelar</a>
                
                                    </div>
                                </div>
                                
                            </div>
                            
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                
                                <strong>Mensaje del Sistema!</strong> No existen Detalle de receta.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Proyecto_2/Clinica/templates/atencion/receta/recetas_pacientes.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                </div>
            </div>
        </div>
        <div class="card-body table-responsive">
            <div class="row">
                <div class="card-title col-md-8 mt-2">
                    <h2 class="text-dark ml-2 font-italic">
                        Consulta de Recetas del paciente. 
                    </h2>
                </div>
                <div class="col-md-4">
                    <div class="float-right m-3">
                        <a class="btn btn-primary btn-sm"
                        href="{% url 'atencion:nuevaReceta' %}?id_paciente={{recetas.paciente.id}}">Nueva Receta</a>
                        <a class="btn btn-primary btn-sm" href="{% url 'atencion:detalle' %}?id_paciente={{recetas.paciente.id}}">Detalle de Receta</a>
                        <a class="btn btn-primary btn-sm" href="{% url 'atencion:toma' %}">Toma de Signos</a>
                        <a class="btn btn-primary btn-sm"
                        href="{% url 'base:paciente' %}">Cancelar</a>
                    </div>
                </div>
            </div>
            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Paciente</th>
                                <th class="text-center">Fecha</th>
                                <th class="text-center">Hora</th>
                                <th class="text-center">Motivo</th>
                                <th class="text-center">Acciones</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for rec in recetas%}
                            <tr>
                                <td class="text-center">{{ rec.paciente.nombre }}</td>
                                <td class="text-center">{{ rec.fecha }}</td>
                                <td class="text-center">{{ rec.hora }}</td>
                                <td class="text-center">{{ rec.motivo }}</td>
                                <td class="text-center"><a class="btn btn-primary btn-sm" href="{% url 'atencion:d' %}?id_rec={{rec.id}}">Detalle de esta Receta</a></td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen Recetas del paceinte registrados.
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Proyecto_2/Clinica/templates/atencion/receta/toma.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-herader rounded-top bg-success shadow p-0">
                    <div class="row">
                        <div class="card-title col-md-8 mt-2">
                            <h2 class="text-light ml-2 font-italic font-weight-bold">
                                Mantenimiento De Recetas 
                            </h2>
                        </div>
                        <div class="col-md-4">
                            <div class="float-right m-3">
                                <a href="{% url 'base:paciente' %}" class="btn btn-primary">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}

                                <button class="btn btn-success btn-block"
                                type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}