Proyecto_2/Clinica/Clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from appbase.views import InicioView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('base/', include('appbase.urls')),
    path('atencion/', include('appconsulta.urls')),
    path('',  auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Proyecto_2/Clinica/appbase/urls.py
from django.urls import path
from .views import(PacienteView, CrearPacienteView, EditarPacienteView, EliminarPacienteView, 
ListadoHorarioView, CrearHorarioView, EditarHorarioView, EliminarHorarioView, ListadoAgendaView,
CrearAgendaView, EditarAgendaView, EliminarAgendaView, DoctorView, CrearDoctoresView, EditarDoctoresView,
EliminarDoctoresView, SignoVitalView, CrearSignoVitalView, EditarSignoVitalView, EliminarSignoVitalView)
app_name = 'base'
urlpatterns = [
    path('paciente/', PacienteView.as_view(), name='paciente'),
    path('crear_paciente/', CrearPacienteView.as_view(), name='crear_paciente'),
    path('editar_paciente/<int:pk>/',
         EditarPacienteView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>/',
         EliminarPacienteView.as_view(), name='eliminar_paciente'),
    path('listar_horario/', ListadoHorarioView.as_view(), name='listar_horario'),
    path('crear_horario/', CrearHorarioView.as_view(), name='crear_horario'),
    path('editar_horario/<int:pk>/', EditarHorarioView.as_view(), name='editar_horario'),
    path('eliminar_horario/<int:pk>/', EliminarHorarioView.as_view(), name='eliminar_horario'),
    path('listar_agenda/', ListadoAgendaView.as_view(), name='listar_agenda'),
    path('crear_agenda/', CrearAgendaView.as_view(), name='crear_agenda'),
    path('editar_agenda/<int:pk>/', EditarAgendaView.as_view(), name='editar_agenda'),
    path('eliminar_agenda/<int:pk>/', EliminarAgendaView.as_view(), name='eliminar_agenda'),
    path('listar_doctores/', DoctorView.as_view(), name='listar_doctores'),
    path('crear_doctores/', CrearDoctoresView.as_view(), name='crear_doctores'),
    path('editar_doctores/<int:pk>/',
         EditarDoctoresView.as_view(), name='editar_doctores'),
    path('eliminar_doctores/<int:pk>/',
         EliminarDoctoresView.as_view(), name='eliminar_doctores'),
    path('listar_signovital/', SignoVitalView.as_view(), name='listar_signovital'),
    path('crear_signovital/', CrearSignoVitalView.as_view(), name='crear_signovital'),
    path('editar_signovital/<int:pk>/', EditarSignoVitalView.as_view(), name='editar_signovital'),
    path('eliminar_signovital/<int:pk>/', EliminarSignoVitalView.as_view(), name='eliminar_signovital'),
]

Proyecto_2/Clinica/templates/base/horario/crear_horario.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-herader rounded-top bg-success shadow p-0">
                    <div class="row">
                        <div class="card-title col-md-8 mt-2">
                            <h2 class="text-light ml-2 font-italic font-weight-bold">
                                Mantenimiento De Horarios de Atenciones
                            </h2>
                        </div>
                        <div class="col-md-4">
                            <div class="float-right m-3">
                                <a href="{% url 'base:listar_horario' %}" class="btn btn-primary">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}

                                <button class="btn btn-success btn-block"
                                type="submit">Registrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

Proyecto_2/Clinica/templates/base/horario/listar_horario.html
{% extends 'base.html' %}
{% block header %}
{% include 'header.html' %}
{% endblock %}
{% block main %}
{% load static %}
<div class="container-fluid" style="margin-top: 3rem;">
    <div class="card">
        <div class="card-header bg-success text-light ">
            <div class="row">
                <div class="col-md-8">
                </div>
            </div>
        </div>
        <div class="card-body table-responsive">
            <div class="row">
                <div class="card-title col-md-8 mt-2">
                    <h2 class="text-dark ml-2 font-italic">
                        Consulta de Horarios
                    </h2>
                </div>
                <div class="col-md-4">
                    <div class="float-right m-3">
                        <a href="{% url 'base:crear_horario' %}" id="id_nuevo" class="btn btn-primary">
                            Nuevo Registro
                        </a>
                    </div>
                </div>
            </div>
            <div class="row pt-2">
                <div class="col">
                    <table class="table table-striped table-hover table-sm  ">

                        <thead>
                            <tr>
                                <th class="text-center">Dia</th>
                                <th class="text-center">Desde</th>
                                <th class="text-center">Hasta</th>
                                <th class="text-center">Estado</th>
                                <th class="text-center">Acciones</th>
                            </tr>

                        </thead>
                        <tbody id="tabla">
                            {% for horario in Horarios%}
                            <tr>
                                <td class="text-center">{{ horario.dia_semana }}</td>
                                <td class="text-center">{{ horario.desde }}</td>
                                <td class="text-center">{{ horario.hasta }}</td>
                                {% if horario.estado %}
                                  <td class="text-center"><samp class="badge 
                                        badge-pill badge-primary">Activo</samp></td>
                                {% else %}
                                   <td class="text-center"><samp class="badge 
                                        badge-pill badge-danger">Deshuso</samp></td>
                                {% endif %}
                                <td class="text-center"><a class="btn btn-primary btn-sm"
                                    href="{% url 'base:editar_horario' horario.id %}">Editar</a>
                                    <a rel="action" data-json='{"accion":"elim" ,"id":"{{horario.id}}"}'
                                        class="btn btn-danger btn-sm" href="#">Eliminar</a>
                                </td>
                            </tr>
                            {% empty %}
                            <div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
                                <strong>Mensaje del Sistema!</strong> No existen Horarios registrados
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- Menú de paginación -->
            {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item ">
                        <a class="page-link"
                            href="?nombre={{nombre}}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                    </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if i <= page_obj.number|add:2 and i >= page_obj.number|add:-2 %}
                    {% if page_obj.number == i %}
                    <li class="page-item active" style="pointer-events:none">
                        <a href="#" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{ forloop.counter }}{{ url }}" class="page-link">{{ forloop.counter }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item ">
                        <a class="page-link" href="?nombre={{nombre}}&page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            <!-- Fin del pagineo -->
        </div>
    </div>



</div>
{% endblock %}

{% block frmodal %}
<!-- inicio formulario Modal para Eliminar -->

<div class="modal fade" id="myModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="frmEliminar" id="frmEliminar" method="POST" action="{% url 'base:eliminar_horario' 0 %} ">
                {% csrf_token %}
                <div class="modal-header bg-primary text-light">
                    <h3 class="modal-title ml-5 font-weight-bold">Mensaje Del Sistema</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" id="id" value="">
                    <input type="hidden" name="action" value="elim">
                    <div class="h3 text-center">
                        <label class="text-primary font-weight-bold">Esta Seguro De Eliminar El Dia:</label>
                        <span class="text-light font-weight-bold badge badge-danger badge-pill"
                            id="descripcion"></span><br>

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Final Formulario Modal-->
{% endblock %}

{% block jscript %}
<script>
    $(function () {

        $('#tabla').on('click', 'a[rel="action"]', function () {
            let data = $(this).data('json'),
                action = data.accion,
                id = data.id;
            let desc = $(this).parents('tr').children('td').eq(0).html();
            $('#descripcion').html(desc);
            $('#frmEliminar #id').val(id);
            $('#myModal').modal('show');
            return;

        });

    })

    function convertir() {
        let titulo = document.getElementById("titulo").innerText
        document.getElementById("titulo").innerText = titulo.toUpperCase()
        alert(titulo)
    }
</script>
{% endblock %}